-- -------------------------------------------------------------
-- data_insert_cocktails.sql – Seed data for cocktails & ingredients
-- ⚠️  Auto-generated by scripts/generate_cocktail_inserts.py
--      DO NOT EDIT MANUALLY
-- -------------------------------------------------------------

-- Cocktail: Negroni
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('negroni', 'Negroni', 'old-fashioned', 'Before Dinner Cocktail', 'Half an orange slice', 'Build into old-fashioned glass filled with ice. Stir gently.', 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Negroni_served_in_Vancouver_BC.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 3, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000007', 3, 'cl', NULL, NULL) /* Campari */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000049', 3, 'cl', 'Sweet red vermouth', NULL) /* Vermouth */;

-- Cocktail: Old Fashioned
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('old-fashioned', 'Old Fashioned', 'old-fashioned', 'Before Dinner Cocktail', 'Orange slice and cherry', 'Place sugar cube in old-fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolve. Fill the glass with ice cubes and add whisky.', 'https://upload.wikimedia.org/wikipedia/commons/5/56/15-09-26-RalfR-WLC-0141.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000051', 4.5, 'cl', 'Bourbon or rye whiskey', NULL) /* Whiskey */;

-- Cocktail: Tuxedo
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('tuxedo', 'Tuxedo', 'martini', 'All Day Cocktail', 'Cherry and lemon twist', 'Stir all ingredients with ice and strain into cocktail glass.', 'https://upload.wikimedia.org/wikipedia/commons/9/93/Tuxedo_No._2_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 3, 'cl', 'Old Tom Gin', NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000049', 3, 'cl', 'Dry vermouth', NULL) /* Vermouth */;

-- Cocktail: Mojito
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('mojito', 'Mojito', 'collins', 'Longdrink', 'Mint leaves and lemon slice', 'Muddle mint sprigs with sugar and lime juice. Add splash of soda water and fill glass with cracked ice. Pour rum and top with soda water. Serve with straw.', 'https://iba-world.com/wp-content/uploads/2020/12/mojito.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000052', 4, 'cl', 'White Cuban Rum', NULL) /* White rum */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000033', 3, 'cl', NULL, NULL) /* Lime juice */;

-- Cocktail: Horse's Neck
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('horses-neck', 'Horse''s Neck', 'highball', 'Longdrink', 'Lemon twist', 'Build into highball glass with ice cubes. Stir gently. If required, add dashes of Angostura bitters.', 'https://iba-world.com/wp-content/uploads/2020/12/horses-neck.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000012', 4, 'cl', NULL, NULL) /* Cognac */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000026', 12, 'cl', NULL, NULL) /* Ginger Ale */;

-- Cocktail: Planter's Punch
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('planters-punch', 'Planter''s Punch', 'highball', 'Longdrink', 'Pineapple slice and a cherry', 'Pour all ingredients, except the bitters, into shaker filled with ice. Shake. Pour into large glass, filled with ice. Add Angostura bitters, “on top”.', 'https://iba-world.com/wp-content/uploads/2020/12/planters-punch.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000018', 4.5, 'cl', NULL, NULL) /* Dark rum */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000036', 3.5, 'cl', NULL, NULL) /* Orange juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000039', 3.5, 'cl', NULL, NULL) /* Pineapple juice */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000031', 2, 'cl', NULL, NULL) /* Lemon juice */,
    ((SELECT id FROM new_cocktail), 5, '00000000-0000-0000-0000-000000000045', 1, 'cl', 'Grenadine', NULL) /* Syrup */,
    ((SELECT id FROM new_cocktail), 6, '00000000-0000-0000-0000-000000000045', 1, 'cl', 'Sugar syrup', NULL) /* Syrup */;

-- Cocktail: Sea Breeze
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('sea-breeze', 'Sea Breeze', 'highball', 'Longdrink', 'Lime wedge', 'Build all ingredients in a rock glass filled with ice.', 'https://iba-world.com/wp-content/uploads/2020/12/sea-breeze.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000050', 4, 'cl', NULL, NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000014', 12, 'cl', NULL, NULL) /* Cranberry juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000028', 3, 'cl', NULL, NULL) /* Grapefruit juice */;

-- Cocktail: Pisco Sour
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('pisco-sour', 'Pisco Sour', 'old-fashioned', 'All Day Cocktail', NULL, 'Shake and strain into a chilled champagne flute. Dash some Angostura bitters on top.', 'https://iba-world.com/wp-content/uploads/2020/12/pisco-sour.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000040', 4.5, 'cl', NULL, NULL) /* Pisco */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000031', 3, 'cl', NULL, NULL) /* Lemon juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000045', 2, 'cl', 'Sugar syrup', NULL) /* Syrup */;

-- Cocktail: Long Island Iced Tea
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('long-island-iced-tea', 'Long Island Iced Tea', 'highball', 'Longdrink', 'Lemon twist', 'Add all ingredients into highball glass filled with ice. Stir gently. Serve with straw.', 'https://iba-world.com/wp-content/uploads/2020/12/long-island-iced-tea.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000046', 1.5, 'cl', NULL, NULL) /* Tequila */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000050', 1.5, 'cl', NULL, NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000052', 1.5, 'cl', NULL, NULL) /* White rum */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000048', 1.5, 'cl', NULL, NULL) /* Triple Sec */,
    ((SELECT id FROM new_cocktail), 5, '00000000-0000-0000-0000-000000000025', 1.5, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 6, '00000000-0000-0000-0000-000000000031', 2.5, 'cl', NULL, NULL) /* Lemon juice */,
    ((SELECT id FROM new_cocktail), 7, '00000000-0000-0000-0000-000000000045', 3.0, 'cl', 'Gomme syrup', NULL) /* Syrup */;

-- Cocktail: Clover Club
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('clover-club', 'Clover Club', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/clover-club.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 4.5, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000045', 1.5, 'cl', 'Raspberry syrup', NULL) /* Syrup */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000031', 1.5, 'cl', NULL, NULL) /* Lemon juice */;

-- Cocktail: Angel Face
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('angel-face', 'Angel Face', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into a cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/angel-face.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 3, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000003', 3, 'cl', NULL, NULL) /* Apricot brandy */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000006', 3, 'cl', NULL, NULL) /* Calvados */;

-- Cocktail: Mimosa
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('mimosa', 'Mimosa', 'champagne-flute', 'Sparkling Cocktail', 'Optional orange twist', 'Pour orange juice into flute and gently pour Champagne. Stir gently. Note: Buck''s Fizz is a very similar cocktail but made of two parts champagne to one part orange juice.', 'https://iba-world.com/wp-content/uploads/2020/12/mimosa.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000008', 7.5, 'cl', NULL, NULL) /* Champagne */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000036', 7.5, 'cl', NULL, NULL) /* Orange juice */;

-- Cocktail: Whiskey Sour
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('whiskey-sour', 'Whiskey Sour', 'old-fashioned', 'Before Dinner Cocktail', 'Half an orange slice and cherry', 'Dash egg white (Optional: if used shake little harder to foam up the egg white). Pour all ingredients into cocktail shaker filled with ice. Shake. Strain into cocktail glass. If served ‘On the rocks’, strain ingredients into old-fashioned glass filled with ice.', 'https://iba-world.com/wp-content/uploads/2020/12/whiskey-sour.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000051', 4.5, 'cl', 'Bourbon whiskey', NULL) /* Whiskey */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000031', 3.0, 'cl', NULL, NULL) /* Lemon juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000045', 1.5, 'cl', 'Sugar syrup', NULL) /* Syrup */;

-- Cocktail: Screwdriver
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('screwdriver', 'Screwdriver', 'highball', 'All Day Cocktail', 'Orange slice', 'Build into a highball glass filled with ice. Stir gently.', 'https://upload.wikimedia.org/wikipedia/commons/4/45/Screwdriver%2C_Birmingham-Shuttlesworth_International_Airport%2C_Birmingham_AL.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000050', 5, 'cl', NULL, NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000036', 10, 'cl', NULL, NULL) /* Orange juice */;

-- Cocktail: Cuba Libre
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('cuba-libre', 'Cuba Libre', 'highball', 'Longdrink', 'Lime wedge', 'Build all ingredients in a highball glass filled with ice.', 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Cuba_Libre.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000052', 5, 'cl', NULL, NULL) /* White rum */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000013', 12, 'cl', NULL, NULL) /* Cola */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000033', 1, 'cl', NULL, NULL) /* Lime juice */;

-- Cocktail: Manhattan
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('manhattan', 'Manhattan', 'martini', 'Before Dinner Cocktail', 'Cherry', 'Stir in mixing glass with ice cubes. Strain into chilled cocktail glass.', 'https://upload.wikimedia.org/wikipedia/commons/2/25/Rum_Manhattan_cocktail_with_Maraschino_caviar.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000051', 5, 'cl', 'Rye whiskey', NULL) /* Whiskey */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000049', 2, 'cl', 'Red vermouth', NULL) /* Vermouth */;

-- Cocktail: Porto Flip
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('porto-flip', 'Porto Flip', 'martini', 'After Dinner Cocktail', NULL, 'Shake with ice cubes. Strain into cocktail glass. Sprinkle with fresh ground nutmeg.', 'https://iba-world.com/wp-content/uploads/2020/12/porto-flip.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000012', 1.5, 'cl', NULL, NULL) /* Cognac */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000043', 4.5, 'cl', NULL, NULL) /* Red Port */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000023', 1, 'cl', NULL, NULL) /* Egg yolk */;

-- Cocktail: Gin Fizz
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('gin-fizz', 'Gin Fizz', 'highball', 'Longdrink', 'Lemon slice', 'Shake all ingredients with ice cubes, except soda water. Pour into tumbler. Top with soda water.', 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Gin_Fizz_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 4.5, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000031', 3, 'cl', NULL, NULL) /* Lemon juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000045', 1, 'cl', 'Sugar syrup', NULL) /* Syrup */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000044', 8, 'cl', NULL, NULL) /* Soda water */;

-- Cocktail: Espresso Martini
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('espresso-martini', 'Espresso Martini', 'martini', 'After Dinner Cocktail', NULL, 'Shake and strain into a chilled cocktail glass.', 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Espresso_Martini_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000050', 5, 'cl', NULL, NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000011', 1, 'cl', 'Kahlúa', NULL) /* Coffee liqueur */;

-- Cocktail: Margarita
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('margarita', 'Margarita', 'margarita', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into cocktail glass rimmed with salt (note:Fruit Margarita - blend selected fruit with the above recipe).', 'https://upload.wikimedia.org/wikipedia/commons/6/6b/MargaritaReal.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000046', 3.5, 'cl', NULL, NULL) /* Tequila */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000048', 2, 'cl', 'Cointreau', NULL) /* Triple Sec */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000033', 1.5, 'cl', NULL, NULL) /* Lime juice */;

-- Cocktail: Aviation
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('aviation', 'Aviation', 'martini', 'All Day Cocktail', NULL, 'Shake and strain into a chilled cocktail glass.', 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Aviation_Cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 4.5, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000009', 1.5, 'cl', 'Maraschino', NULL) /* Cherry liqueur */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000031', 1.5, 'cl', NULL, NULL) /* Lemon juice */;

-- Cocktail: Bellini
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('bellini', 'Bellini', 'champagne-flute', 'Sparkling Cocktail', NULL, 'Pour peach puree into chilled glass and add sparkling wine. Stir gently. Variations: Puccini (fresh mandarin juice), Rossini (fresh strawberry puree), Tintoretto (fresh pomegranate juice)', 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Bellini_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000041', 10, 'cl', NULL, NULL) /* Prosecco */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000037', 5, 'cl', NULL, NULL) /* Peach puree */;

-- Cocktail: Grasshopper
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('grasshopper', 'Grasshopper', 'martini', 'After Dinner Cocktail', NULL, 'Shake with ice cubes. Strain into chilled cocktail glass.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Grasshopper_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000017', 3, 'cl', 'White Créme de Cacao', NULL) /* Créme liqueur */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000017', 3, 'cl', 'Green Créme de Menthe', NULL) /* Créme liqueur */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000015', 3, 'cl', NULL, NULL) /* Cream */;

-- Cocktail: Tequila Sunrise
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('tequila-sunrise', 'Tequila Sunrise', 'highball', 'Longdrink', 'Orange slice and a cherry', 'Build tequila and orange juice into highball with ice cubes. Add a splash of grenadine to create sunrise effect. Do not stir.', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Tequila_Sunrise_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000046', 4.5, 'cl', NULL, NULL) /* Tequila */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000036', 9, 'cl', NULL, NULL) /* Orange juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000045', 1.5, 'cl', 'Grenadine', NULL) /* Syrup */;

-- Cocktail: Daiquiri
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('daiquiri', 'Daiquiri', 'martini', 'Before Dinner Cocktail', NULL, 'Shake and strain into a cocktail glass.', 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Daiquiri_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000052', 4.5, 'cl', NULL, NULL) /* White rum */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000033', 2.5, 'cl', NULL, NULL) /* Lime juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000045', 1.5, 'cl', 'Simple syrup', NULL) /* Syrup */;

-- Cocktail: Rusty Nail
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('rusty-nail', 'Rusty Nail', 'old-fashioned', 'After Dinner Cocktail', 'Lemon twist', 'Build into old-fashioned glass filled with ice. Stir gently.', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Rusty_Nail_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000051', 4.5, 'cl', 'Scotch whisky', NULL) /* Whiskey */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000021', 2.5, 'cl', NULL, NULL) /* Drambuie */;

-- Cocktail: Stinger
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('stinger', 'Stinger', 'martini', 'After Dinner Cocktail', NULL, 'Stir in mixing glass with ice cubes. Strain into a cocktail glass.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Stinger_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000012', 5, 'cl', NULL, NULL) /* Cognac */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000017', 2, 'cl', 'White Créme de Menthe', NULL) /* Créme liqueur */;

-- Cocktail: Golden Dream
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('golden-dream', 'Golden Dream', 'martini', 'After Dinner Cocktail', NULL, 'Shake with ice cubes. Strain into chilled cocktail glass.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Golden_Dream_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000024', 2, 'cl', NULL, NULL) /* Galliano */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000048', 2, 'cl', NULL, NULL) /* Triple Sec */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000036', 2, 'cl', NULL, NULL) /* Orange juice */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000015', 1, 'cl', NULL, NULL) /* Cream */;

-- Cocktail: Bramble
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('bramble', 'Bramble', 'old-fashioned', 'All Day Cocktail', 'Lemon slice and two blackberries', 'Build over crushed ice, in a rock glass. Stir, then pour the blackberry liqueur over the top of the drink in a circular fashion.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Bramble_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 4, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000031', 1.5, 'cl', NULL, NULL) /* Lemon juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000045', 1, 'cl', 'Sugar syrup', NULL) /* Syrup */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000004', 1.5, 'cl', NULL, NULL) /* Blackberry liqueur */;

-- Cocktail: Alexander
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('alexander', 'Alexander', 'martini', NULL, NULL, 'Shake and strain into a chilled cocktail glass. Sprinkle with fresh ground nutmeg.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Alexander_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000012', 3, 'cl', NULL, NULL) /* Cognac */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000017', 3, 'cl', 'Brown Créme de Cacao', NULL) /* Créme liqueur */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000015', 3, 'cl', NULL, NULL) /* Cream */;

-- Cocktail: Black Russian
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('black-russian', 'Black Russian', 'old-fashioned', 'After Dinner Cocktail', NULL, 'Build into old fashioned glass filled with ice cubes. Stir gently. Note: for White Russian, float fresh cream on the top and stir gently.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Black_Russian_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000050', 5, 'cl', NULL, NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000011', 2, 'cl', NULL, NULL) /* Coffee liqueur */;

-- Cocktail: Bloody Mary
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('bloody-mary', 'Bloody Mary', 'highball', 'Longdrink', 'Celery and optionally lemon wedge', 'Stir gently, pour all ingredients into highball glass.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Bloody_Mary_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000050', 4.5, 'cl', NULL, NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000047', 9, 'cl', NULL, NULL) /* Tomato juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000031', 1.5, 'cl', NULL, NULL) /* Lemon juice */;

-- Cocktail: Sex on the Beach
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('sex-on-the-beach', 'Sex on the Beach', 'highball', 'Longdrink', 'Orange slice', 'Build all ingredients in a highball glass filled with ice.', 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Sex_on_the_Beach_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000050', 4, 'cl', NULL, NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000038', 2, 'cl', NULL, NULL) /* Peach schnapps */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000014', 4, 'cl', NULL, NULL) /* Cranberry juice */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000036', 4, 'cl', NULL, NULL) /* Orange juice */;

-- Cocktail: Monkey Gland
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('monkey-gland', 'Monkey Gland', 'martini', 'All Day Cocktail', NULL, 'Shake and strain into a chilled cocktail glass.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Monkey_Gland_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 5, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000036', 3, 'cl', NULL, NULL) /* Orange juice */;

-- Cocktail: Sidecar
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('sidecar', 'Sidecar', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into cocktail glass.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Sidecar_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000012', 5, 'cl', NULL, NULL) /* Cognac */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000048', 2, 'cl', NULL, NULL) /* Triple Sec */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000031', 2, 'cl', NULL, NULL) /* Lemon juice */;

-- Cocktail: Irish Coffee
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('irish-coffee', 'Irish Coffee', 'hot-drink', 'Hot Drink', NULL, 'Warm the Irish whiskey over a burner. Pour into the glass (for hot drink) hot coffee, and add a teaspoon of sugar. Float Cream on top.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Irish_Coffee_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000051', 4, 'cl', 'Irish whiskey', NULL) /* Whiskey */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000029', 9, 'cl', NULL, NULL) /* Hot coffee */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000015', 3, 'cl', NULL, NULL) /* Cream */;

-- Cocktail: Sazerac
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('sazerac', 'Sazerac', 'old-fashioned', 'After Dinner Cocktail', 'Lemon twist', 'Rinse a chilled old-fashioned glass with the absinthe, add crushed ice and set it aside. Stir the remaining ingredients over ice and set it aside. Discard the ice and any excess absinthe from the prepared glass, and strain the drink into the glass. Note: The original recipe changed after the American Civil War, rye whiskey substituted cognac as it became hard to obtain.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Sazerac_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000012', 5, 'cl', NULL, NULL) /* Cognac */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000001', 1, 'cl', NULL, NULL) /* Absinthe */;

-- Cocktail: Americano
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('americano', 'Americano', 'old-fashioned', 'Before Dinner Cocktail', 'Half an orange slice', 'Build into old fashioned glass filled with ice cubes. Add a splash of soda water.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Americano_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000007', 3, 'cl', NULL, NULL) /* Campari */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000049', 3, 'cl', 'Red vermouth', NULL) /* Vermouth */;

-- Cocktail: Singapore Sling
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('singapore-sling', 'Singapore Sling', 'highball', 'Longdrink', 'Pineapple slice and a cherry', 'Shake with ice cubes. Strain into highball glass.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Singapore_Sling_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 3, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000009', 1.5, 'cl', NULL, NULL) /* Cherry liqueur */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000048', 0.75, 'cl', 'Cointreau', NULL) /* Triple Sec */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000020', 0.75, 'cl', NULL, NULL) /* DOM Bénédictine */,
    ((SELECT id FROM new_cocktail), 5, '00000000-0000-0000-0000-000000000039', 12.0, 'cl', NULL, NULL) /* Pineapple juice */,
    ((SELECT id FROM new_cocktail), 6, '00000000-0000-0000-0000-000000000033', 1.5, 'cl', NULL, NULL) /* Lime juice */,
    ((SELECT id FROM new_cocktail), 7, '00000000-0000-0000-0000-000000000045', 1, 'cl', 'Grenadine', NULL) /* Syrup */;

-- Cocktail: Moscow Mule
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('moscow-mule', 'Moscow Mule', 'highball', 'Longdrink', 'Lime slice', 'Combine the vodka and ginger beer. Add lime juice.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Moscow_Mule_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000050', 4.5, 'cl', NULL, NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000027', 12, 'cl', NULL, NULL) /* Ginger beer */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000033', 0.5, 'cl', NULL, NULL) /* Lime juice */;

-- Cocktail: John Collins
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('john-collins', 'John Collins', 'highball', 'Longdrink', 'Lemon slice and a cherry', 'Build into highball glass filled with ice. Stir gently. Add a dash of Angostura bitters. (Note: Use Old Tom Gin for Tom Collins)', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/John_Collins_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 4.5, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000031', 3, 'cl', NULL, NULL) /* Lemon juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000045', 1.5, 'cl', 'Sugar syrup', NULL) /* Syrup */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000044', 6, 'cl', NULL, NULL) /* Soda water */;

-- Cocktail: Kir
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('kir', 'Kir', 'white-wine', 'Before Dinner Cocktail', NULL, 'Pour Créme de Cassis into glass, top up with white wine. For Kir Royal: Use champagne instead of white wine.', 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Kir_cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000022', 9, 'cl', NULL, NULL) /* Dry White Wine */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000017', 1, 'cl', 'Créme de Cassis', NULL) /* Créme liqueur */;

-- Cocktail: Mint Julep
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('mint-julep', 'Mint Julep', 'highball', 'Longdrink', 'Mint sprig', 'In a highball glass gently muddle the mint, sugar and water. Fill the glass with cracked ice, add Bourbon and stir well until the glass is frost.', 'https://iba-world.com/wp-content/uploads/2020/12/mint-julep.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000051', 6, 'cl', 'Bourbon whiskey', NULL) /* Whiskey */;

-- Cocktail: Paradise
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('paradise', 'Paradise', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/paradise.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 3.5, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000003', 2, 'cl', NULL, NULL) /* Apricot brandy */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000036', 1.5, 'cl', NULL, NULL) /* Orange juice */;

-- Cocktail: Champagne Cocktail
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('champagne-cocktail', 'Champagne Cocktail', 'champagne-flute', 'Sparkling Cocktail', 'Orange slice and a cherry', 'Add dash of Angostura bitter onto sugar cube and drop it into champagne flute. Add cognac followed by pouring gently chilled champagne.', 'https://iba-world.com/wp-content/uploads/2020/12/champagne-cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000008', 9, 'cl', NULL, NULL) /* Champagne */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000012', 1, 'cl', NULL, NULL) /* Cognac */;

-- Cocktail: Mary Pickford
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('mary-pickford', 'Mary Pickford', 'martini', 'All Day Cocktail', NULL, 'Shake and strain into a chilled large cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/mary-pickford.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000052', 6, 'cl', NULL, NULL) /* White rum */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000009', 1, 'cl', 'Maraschino', NULL) /* Cherry liqueur */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000039', 6, 'cl', NULL, NULL) /* Pineapple juice */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000045', 1, 'cl', 'Grenadine', NULL) /* Syrup */;

-- Cocktail: Hemingway Special
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('hemingway-special', 'Hemingway Special', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into a double cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/hemingway-special.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000052', 6, 'cl', NULL, NULL) /* White rum */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000028', 4, 'cl', NULL, NULL) /* Grapefruit juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000009', 1.5, 'cl', 'Maraschino', NULL) /* Cherry liqueur */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000033', 1.5, 'cl', NULL, NULL) /* Lime juice */;

-- Cocktail: Dark 'n' Stormy
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('dark-n-stormy', 'Dark ''n'' Stormy', 'highball', 'Longdrink', 'Lime wedge', 'Build into highball glass filled with ice. Add rum first and top it with ginger beer.', 'https://iba-world.com/wp-content/uploads/2020/12/dark-n-stormy.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000018', 6, 'cl', NULL, NULL) /* Dark rum */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000027', 10, 'cl', NULL, NULL) /* Ginger beer */;

-- Cocktail: Russian Spring Punch
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('russian-spring-punch', 'Russian Spring Punch', 'highball', 'Sparkling Cocktail', 'Lemon slice and a blackberry', 'Shake the ingredients and pour into highball glass. Top with Sparkling wine.', 'https://iba-world.com/wp-content/uploads/2020/12/russian-spring-punch.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000050', 2.5, 'cl', NULL, NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000031', 2.5, 'cl', NULL, NULL) /* Lemon juice */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000017', 1.5, 'cl', 'Créme de Cassis', NULL) /* Créme liqueur */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000045', 1, 'cl', 'Sugar syrup', NULL) /* Syrup */;

-- Cocktail: Cosmopolitan
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('cosmopolitan', 'Cosmopolitan', 'martini', 'All Day Cocktail', 'Lime slice', 'Shake with ice cubes. Strain into a large cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/cosmopolitan.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000050', 4, 'cl', 'Citron Vodka', NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000048', 1.5, 'cl', 'Cointreau', NULL) /* Triple Sec */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000033', 1.5, 'cl', NULL, NULL) /* Lime juice */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000014', 3, 'cl', NULL, NULL) /* Cranberry juice */;

-- Cocktail: Dry Martini
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('dry-martini', 'Dry Martini', 'martini', 'Before Dinner Cocktail', NULL, 'Stir in mixing glass with ice cubes. Strain into chilled martini glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.', 'https://iba-world.com/wp-content/uploads/2020/12/dry-martini.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 6, 'cl', NULL, NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000049', 1, 'cl', 'Dry vermouth', NULL) /* Vermouth */;

-- Cocktail: Between the Sheets
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('between-the-sheets', 'Between the Sheets', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/between-the-sheets.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000052', 3, 'cl', NULL, NULL) /* White rum */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000012', 3, 'cl', NULL, NULL) /* Cognac */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000048', 3, 'cl', NULL, NULL) /* Triple Sec */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000031', 2, 'cl', NULL, NULL) /* Lemon juice */;

-- Cocktail: Casino
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('casino', 'Casino', 'martini', 'All Day Cocktail', 'Lemon twist and a cherry', 'Shake with ice cubes. Strain into chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/casino.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000025', 4, 'cl', 'Old Tom Gin', NULL) /* Gin */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000009', 1, 'cl', 'Maraschino', NULL) /* Cherry liqueur */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000035', 1, 'cl', NULL, NULL) /* Orange Bitters */,
    ((SELECT id FROM new_cocktail), 4, '00000000-0000-0000-0000-000000000031', 1, 'cl', NULL, NULL) /* Lemon juice */;

-- Cocktail: Caipirinha
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('caipirinha', 'Caipirinha', 'old-fashioned', 'All Day Cocktail', NULL, 'Place lime and sugar in old fashion glass and muddle. Fill glass with ice and Cachaca (note:Caipiroska- use Vodka instead of Cachaca).', 'https://iba-world.com/wp-content/uploads/2020/12/caipirinha.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000005', 5, 'cl', NULL, NULL) /* Cachaca */;

-- Cocktail: Harvey Wallbanger
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('harvey-wallbanger', 'Harvey Wallbanger', 'highball', 'All Day Cocktail', 'Orance slice and a cherry', 'Build vodka and orange juice into a highball glass filled with ice. Stir gently and float Galliano on top.', 'https://iba-world.com/wp-content/uploads/2020/12/harvey-wallbanger.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, '00000000-0000-0000-0000-000000000050', 4.5, 'cl', NULL, NULL) /* Vodka */,
    ((SELECT id FROM new_cocktail), 2, '00000000-0000-0000-0000-000000000024', 1.5, 'cl', NULL, NULL) /* Galliano */,
    ((SELECT id FROM new_cocktail), 3, '00000000-0000-0000-0000-000000000036', 9, 'cl', NULL, NULL) /* Orange juice */;
