-- -------------------------------------------------------------
-- data_insert_cocktails.sql – Seed data for cocktails & ingredients
-- ⚠️  Auto-generated by scripts/generate_cocktail_inserts.py
--      DO NOT EDIT MANUALLY
-- -------------------------------------------------------------

-- Cocktail: Negroni
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('negroni', 'Negroni', 'old-fashioned', 'Before Dinner Cocktail', 'Half an orange slice', 'Build into old-fashioned glass filled with ice. Stir gently.', 'https://iba-world.com/wp-content/uploads/2020/12/negroni.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Campari')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Vermouth')), 3, 'cl', 'Sweet red vermouth', NULL);

-- Cocktail: Old Fashioned
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('old-fashioned', 'Old Fashioned', 'old-fashioned', 'Before Dinner Cocktail', 'Orange slice and cherry', 'Place sugar cube in old-fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolve. Fill the glass with ice cubes and add whisky.', 'https://iba-world.com/wp-content/uploads/2020/12/old-fashioned.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Whiskey')), 4.5, 'cl', 'Bourbon or rye whiskey', NULL);

-- Cocktail: Tuxedo
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('tuxedo', 'Tuxedo', 'martini', 'All Day Cocktail', 'Cherry and lemon twist', 'Stir all ingredients with ice and strain into cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/tuxedo.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 3, 'cl', 'Old Tom Gin', NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Vermouth')), 3, 'cl', 'Dry vermouth', NULL);

-- Cocktail: Mojito
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('mojito', 'Mojito', 'collins', 'Longdrink', 'Mint leaves and lemon slice', 'Muddle mint sprigs with sugar and lime juice. Add splash of soda water and fill glass with cracked ice. Pour rum and top with soda water. Serve with straw.', 'https://iba-world.com/wp-content/uploads/2020/12/mojito.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('White rum')), 4, 'cl', 'White Cuban Rum', NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Lime juice')), 3, 'cl', NULL, NULL);

-- Cocktail: Horse's Neck
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('horses-neck', 'Horse''s Neck', 'highball', 'Longdrink', 'Lemon twist', 'Build into highball glass with ice cubes. Stir gently. If required, add dashes of Angostura bitters.', 'https://iba-world.com/wp-content/uploads/2020/12/horses-neck.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Cognac')), 4, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Ginger Ale')), 12, 'cl', NULL, NULL);

-- Cocktail: Planter's Punch
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('planters-punch', 'Planter''s Punch', 'highball', 'Longdrink', 'Pineapple slice and a cherry', 'Pour all ingredients, except the bitters, into shaker filled with ice. Shake. Pour into large glass, filled with ice. Add Angostura bitters, “on top”.', 'https://iba-world.com/wp-content/uploads/2020/12/planters-punch.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Dark rum')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Orange juice')), 3.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Pineapple juice')), 3.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 2, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 5, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1, 'cl', 'Grenadine', NULL),
    ((SELECT id FROM new_cocktail), 6, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1, 'cl', 'Sugar syrup', NULL);

-- Cocktail: Sea Breeze
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('sea-breeze', 'Sea Breeze', 'highball', 'Longdrink', 'Lime wedge', 'Build all ingredients in a rock glass filled with ice.', 'https://iba-world.com/wp-content/uploads/2020/12/sea-breeze.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 4, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Cranberry juice')), 12, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Grapefruit juice')), 3, 'cl', NULL, NULL);

-- Cocktail: Pisco Sour
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('pisco-sour', 'Pisco Sour', 'old-fashioned', 'All Day Cocktail', NULL, 'Shake and strain into a chilled champagne flute. Dash some Angostura bitters on top.', 'https://iba-world.com/wp-content/uploads/2020/12/pisco-sour.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Pisco')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 2, 'cl', 'Sugar syrup', NULL);

-- Cocktail: Long Island Iced Tea
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('long-island-iced-tea', 'Long Island Iced Tea', 'highball', 'Longdrink', 'Lemon twist', 'Add all ingredients into highball glass filled with ice. Stir gently. Serve with straw.', 'https://iba-world.com/wp-content/uploads/2020/12/long-island-iced-tea.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Tequila')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('White rum')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Triple Sec')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 5, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 6, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 2.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 7, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 3.0, 'cl', 'Gomme syrup', NULL);

-- Cocktail: Clover Club
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('clover-club', 'Clover Club', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/clover-club.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1.5, 'cl', 'Raspberry syrup', NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 1.5, 'cl', NULL, NULL);

-- Cocktail: Angel Face
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('angel-face', 'Angel Face', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into a cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/angel-face.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Apricot brandy')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Calvados')), 3, 'cl', NULL, NULL);

-- Cocktail: Mimosa
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('mimosa', 'Mimosa', 'champagne-flute', 'Sparkling Cocktail', 'Optional orange twist', 'Pour orange juice into flute and gently pour Champagne. Stir gently. Note: Buck''s Fizz is a very similar cocktail but made of two parts champagne to one part orange juice.', 'https://iba-world.com/wp-content/uploads/2020/12/mimosa.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Champagne')), 7.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Orange juice')), 7.5, 'cl', NULL, NULL);

-- Cocktail: Whiskey Sour
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('whiskey-sour', 'Whiskey Sour', 'old-fashioned', 'Before Dinner Cocktail', 'Half an orange slice and cherry', 'Dash egg white (Optional: if used shake little harder to foam up the egg white). Pour all ingredients into cocktail shaker filled with ice. Shake. Strain into cocktail glass. If served ‘On the rocks’, strain ingredients into old-fashioned glass filled with ice.', 'https://iba-world.com/wp-content/uploads/2020/12/whiskey-sour.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Whiskey')), 4.5, 'cl', 'Bourbon whiskey', NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 3.0, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1.5, 'cl', 'Sugar syrup', NULL);

-- Cocktail: Screwdriver
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('screwdriver', 'Screwdriver', 'highball', 'All Day Cocktail', 'Orange slice', 'Build into a highball glass filled with ice. Stir gently.', 'https://iba-world.com/wp-content/uploads/2020/12/screwdriver.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Orange juice')), 10, 'cl', NULL, NULL);

-- Cocktail: Cuba Libre
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('cuba-libre', 'Cuba Libre', 'highball', 'Longdrink', 'Lime wedge', 'Build all ingredients in a highball glass filled with ice.', 'https://iba-world.com/wp-content/uploads/2020/12/cuba-libre.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('White rum')), 5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Cola')), 12, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Lime juice')), 1, 'cl', NULL, NULL);

-- Cocktail: Manhattan
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('manhattan', 'Manhattan', 'martini', 'Before Dinner Cocktail', 'Cherry', 'Stir in mixing glass with ice cubes. Strain into chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/manhattan.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Whiskey')), 5, 'cl', 'Rye whiskey', NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Vermouth')), 2, 'cl', 'Red vermouth', NULL);

-- Cocktail: Porto Flip
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('porto-flip', 'Porto Flip', 'martini', 'After Dinner Cocktail', NULL, 'Shake with ice cubes. Strain into cocktail glass. Sprinkle with fresh ground nutmeg.', 'https://iba-world.com/wp-content/uploads/2020/12/porto-flip.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Cognac')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Red Port')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Egg yolk')), 1, 'cl', NULL, NULL);

-- Cocktail: Gin Fizz
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('gin-fizz', 'Gin Fizz', 'highball', 'Longdrink', 'Lemon slice', 'Shake all ingredients with ice cubes, except soda water. Pour into tumbler. Top with soda water.', 'https://iba-world.com/wp-content/uploads/2020/12/gin-fizz.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1, 'cl', 'Sugar syrup', NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Soda water')), 8, 'cl', NULL, NULL);

-- Cocktail: Espresso Martini
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('espresso-martini', 'Espresso Martini', 'martini', 'After Dinner Cocktail', NULL, 'Shake and strain into a chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/espresso-martini.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Coffee liqueur')), 1, 'cl', 'Kahlúa', NULL);

-- Cocktail: Margarita
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('margarita', 'Margarita', 'margarita', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into cocktail glass rimmed with salt (note:Fruit Margarita - blend selected fruit with the above recipe).', 'https://iba-world.com/wp-content/uploads/2020/12/margarita.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Tequila')), 3.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Triple Sec')), 2, 'cl', 'Cointreau', NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Lime juice')), 1.5, 'cl', NULL, NULL);

-- Cocktail: Aviation
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('aviation', 'Aviation', 'martini', 'All Day Cocktail', NULL, 'Shake and strain into a chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/aviation.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Cherry liqueur')), 1.5, 'cl', 'Maraschino', NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 1.5, 'cl', NULL, NULL);

-- Cocktail: Bellini
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('bellini', 'Bellini', 'champagne-flute', 'Sparkling Cocktail', NULL, 'Pour peach puree into chilled glass and add sparkling wine. Stir gently. Variations: Puccini (fresh mandarin juice), Rossini (fresh strawberry puree), Tintoretto (fresh pomegranate juice)', 'https://iba-world.com/wp-content/uploads/2020/12/bellini.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Prosecco')), 10, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Peach puree')), 5, 'cl', NULL, NULL);

-- Cocktail: Grasshopper
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('grasshopper', 'Grasshopper', 'martini', 'After Dinner Cocktail', NULL, 'Shake with ice cubes. Strain into chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/grasshopper.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Créme liqueur')), 3, 'cl', 'White Créme de Cacao', NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Créme liqueur')), 3, 'cl', 'Green Créme de Menthe', NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Cream')), 3, 'cl', NULL, NULL);

-- Cocktail: Tequila Sunrise
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('tequila-sunrise', 'Tequila Sunrise', 'highball', 'Longdrink', 'Orange slice and a cherry', 'Build tequila and orange juice into highball with ice cubes. Add a splash of grenadine to create sunrise effect. Do not stir.', 'https://iba-world.com/wp-content/uploads/2020/12/tequila-sunrise.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Tequila')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Orange juice')), 9, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1.5, 'cl', 'Grenadine', NULL);

-- Cocktail: Daiquiri
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('daiquiri', 'Daiquiri', 'martini', 'Before Dinner Cocktail', NULL, 'Shake and strain into a cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/daiquiri.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('White rum')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Lime juice')), 2.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1.5, 'cl', 'Simple syrup', NULL);

-- Cocktail: Rusty Nail
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('rusty-nail', 'Rusty Nail', 'old-fashioned', 'After Dinner Cocktail', 'Lemon twist', 'Build into old-fashioned glass filled with ice. Stir gently.', 'https://iba-world.com/wp-content/uploads/2020/12/rusty-nail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Whiskey')), 4.5, 'cl', 'Scotch whisky', NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Drambuie')), 2.5, 'cl', NULL, NULL);

-- Cocktail: Stinger
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('stinger', 'Stinger', 'martini', 'After Dinner Cocktail', NULL, 'Stir in mixing glass with ice cubes. Strain into a cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/stinger.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Cognac')), 5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Créme liqueur')), 2, 'cl', 'White Créme de Menthe', NULL);

-- Cocktail: Golden Dream
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('golden-dream', 'Golden Dream', 'martini', 'After Dinner Cocktail', NULL, 'Shake with ice cubes. Strain into chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/golden-dream.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Galliano')), 2, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Triple Sec')), 2, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Orange juice')), 2, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Cream')), 1, 'cl', NULL, NULL);

-- Cocktail: Bramble
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('bramble', 'Bramble', 'old-fashioned', 'All Day Cocktail', 'Lemon slice and two blackberries', 'Build over crushed ice, in a rock glass. Stir, then pour the blackberry liqueur over the top of the drink in a circular fashion.', 'https://iba-world.com/wp-content/uploads/2020/12/bramble.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 4, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1, 'cl', 'Sugar syrup', NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Blackberry liqueur')), 1.5, 'cl', NULL, NULL);

-- Cocktail: Alexander
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('alexander', 'Alexander', 'martini', NULL, NULL, 'Shake and strain into a chilled cocktail glass. Sprinkle with fresh ground nutmeg.', 'https://iba-world.com/wp-content/uploads/2020/12/alexander.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Cognac')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Créme liqueur')), 3, 'cl', 'Brown Créme de Cacao', NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Cream')), 3, 'cl', NULL, NULL);

-- Cocktail: Black Russian
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('black-russian', 'Black Russian', 'old-fashioned', 'After Dinner Cocktail', NULL, 'Build into old fashioned glass filled with ice cubes. Stir gently. Note: for White Russian, float fresh cream on the top and stir gently.', 'https://iba-world.com/wp-content/uploads/2020/12/black-russian.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Coffee liqueur')), 2, 'cl', NULL, NULL);

-- Cocktail: Bloody Mary
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('bloody-mary', 'Bloody Mary', 'highball', 'Longdrink', 'Celery and optionally lemon wedge', 'Stir gently, pour all ingredients into highball glass.', 'https://iba-world.com/wp-content/uploads/2020/12/bloody-mary.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Tomato juice')), 9, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 1.5, 'cl', NULL, NULL);

-- Cocktail: Sex on the Beach
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('sex-on-the-beach', 'Sex on the Beach', 'highball', 'Longdrink', 'Orange slice', 'Build all ingredients in a highball glass filled with ice.', 'https://iba-world.com/wp-content/uploads/2020/12/sex-on-the-beach.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 4, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Peach schnapps')), 2, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Cranberry juice')), 4, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Orange juice')), 4, 'cl', NULL, NULL);

-- Cocktail: Monkey Gland
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('monkey-gland', 'Monkey Gland', 'martini', 'All Day Cocktail', NULL, 'Shake and strain into a chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/monkey-gland.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Orange juice')), 3, 'cl', NULL, NULL);

-- Cocktail: Sidecar
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('sidecar', 'Sidecar', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/sidecar.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Cognac')), 5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Triple Sec')), 2, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 2, 'cl', NULL, NULL);

-- Cocktail: Irish Coffee
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('irish-coffee', 'Irish Coffee', 'hot-drink', 'Hot Drink', NULL, 'Warm the Irish whiskey over a burner. Pour into the glass (for hot drink) hot coffee, and add a teaspoon of sugar. Float Cream on top.', 'https://iba-world.com/wp-content/uploads/2020/12/irish-coffee.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Whiskey')), 4, 'cl', 'Irish whiskey', NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Hot coffee')), 9, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Cream')), 3, 'cl', NULL, NULL);

-- Cocktail: Sazerac
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('sazerac', 'Sazerac', 'old-fashioned', 'After Dinner Cocktail', 'Lemon twist', 'Rinse a chilled old-fashioned glass with the absinthe, add crushed ice and set it aside. Stir the remaining ingredients over ice and set it aside. Discard the ice and any excess absinthe from the prepared glass, and strain the drink into the glass. Note: The original recipe changed after the American Civil War, rye whiskey substituted cognac as it became hard to obtain.', 'https://iba-world.com/wp-content/uploads/2020/12/sazerac.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Cognac')), 5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Absinthe')), 1, 'cl', NULL, NULL);

-- Cocktail: Americano
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('americano', 'Americano', 'old-fashioned', 'Before Dinner Cocktail', 'Half an orange slice', 'Build into old fashioned glass filled with ice cubes. Add a splash of soda water.', 'https://iba-world.com/wp-content/uploads/2020/12/americano.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Campari')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Vermouth')), 3, 'cl', 'Red vermouth', NULL);

-- Cocktail: Singapore Sling
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('singapore-sling', 'Singapore Sling', 'highball', 'Longdrink', 'Pineapple slice and a cherry', 'Shake with ice cubes. Strain into highball glass.', 'https://iba-world.com/wp-content/uploads/2020/12/singapore-sling.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Cherry liqueur')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Triple Sec')), 0.75, 'cl', 'Cointreau', NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('DOM Bénédictine')), 0.75, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 5, (SELECT id FROM base_ingredients WHERE slug=slugify('Pineapple juice')), 12.0, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 6, (SELECT id FROM base_ingredients WHERE slug=slugify('Lime juice')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 7, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1, 'cl', 'Grenadine', NULL);

-- Cocktail: Moscow Mule
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('moscow-mule', 'Moscow Mule', 'highball', 'Longdrink', 'Lime slice', 'Combine the vodka and ginger beer. Add lime juice.', 'https://iba-world.com/wp-content/uploads/2020/12/moscow-mule.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Ginger beer')), 12, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Lime juice')), 0.5, 'cl', NULL, NULL);

-- Cocktail: John Collins
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('john-collins', 'John Collins', 'highball', 'Longdrink', 'Lemon slice and a cherry', 'Build into highball glass filled with ice. Stir gently. Add a dash of Angostura bitters. (Note: Use Old Tom Gin for Tom Collins)', 'https://iba-world.com/wp-content/uploads/2020/12/john-collins.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1.5, 'cl', 'Sugar syrup', NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Soda water')), 6, 'cl', NULL, NULL);

-- Cocktail: Kir
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('kir', 'Kir', 'white-wine', 'Before Dinner Cocktail', NULL, 'Pour Créme de Cassis into glass, top up with white wine. For Kir Royal: Use champagne instead of white wine.', 'https://iba-world.com/wp-content/uploads/2020/12/kir.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Dry White Wine')), 9, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Créme liqueur')), 1, 'cl', 'Créme de Cassis', NULL);

-- Cocktail: Mint Julep
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('mint-julep', 'Mint Julep', 'highball', 'Longdrink', 'Mint sprig', 'In a highball glass gently muddle the mint, sugar and water. Fill the glass with cracked ice, add Bourbon and stir well until the glass is frost.', 'https://iba-world.com/wp-content/uploads/2020/12/mint-julep.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Whiskey')), 6, 'cl', 'Bourbon whiskey', NULL);

-- Cocktail: Paradise
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('paradise', 'Paradise', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/paradise.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 3.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Apricot brandy')), 2, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Orange juice')), 1.5, 'cl', NULL, NULL);

-- Cocktail: Champagne Cocktail
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('champagne-cocktail', 'Champagne Cocktail', 'champagne-flute', 'Sparkling Cocktail', 'Orange slice and a cherry', 'Add dash of Angostura bitter onto sugar cube and drop it into champagne flute. Add cognac followed by pouring gently chilled champagne.', 'https://iba-world.com/wp-content/uploads/2020/12/champagne-cocktail.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Champagne')), 9, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Cognac')), 1, 'cl', NULL, NULL);

-- Cocktail: Mary Pickford
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('mary-pickford', 'Mary Pickford', 'martini', 'All Day Cocktail', NULL, 'Shake and strain into a chilled large cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/mary-pickford.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('White rum')), 6, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Cherry liqueur')), 1, 'cl', 'Maraschino', NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Pineapple juice')), 6, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1, 'cl', 'Grenadine', NULL);

-- Cocktail: Hemingway Special
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('hemingway-special', 'Hemingway Special', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into a double cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/hemingway-special.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('White rum')), 6, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Grapefruit juice')), 4, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Cherry liqueur')), 1.5, 'cl', 'Maraschino', NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Lime juice')), 1.5, 'cl', NULL, NULL);

-- Cocktail: Dark 'n' Stormy
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('dark-n-stormy', 'Dark ''n'' Stormy', 'highball', 'Longdrink', 'Lime wedge', 'Build into highball glass filled with ice. Add rum first and top it with ginger beer.', 'https://iba-world.com/wp-content/uploads/2020/12/dark-n-stormy.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Dark rum')), 6, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Ginger beer')), 10, 'cl', NULL, NULL);

-- Cocktail: Russian Spring Punch
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('russian-spring-punch', 'Russian Spring Punch', 'highball', 'Sparkling Cocktail', 'Lemon slice and a blackberry', 'Shake the ingredients and pour into highball glass. Top with Sparkling wine.', 'https://iba-world.com/wp-content/uploads/2020/12/russian-spring-punch.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 2.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 2.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Créme liqueur')), 1.5, 'cl', 'Créme de Cassis', NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Syrup')), 1, 'cl', 'Sugar syrup', NULL);

-- Cocktail: Cosmopolitan
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('cosmopolitan', 'Cosmopolitan', 'martini', 'All Day Cocktail', 'Lime slice', 'Shake with ice cubes. Strain into a large cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/cosmopolitan.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 4, 'cl', 'Citron Vodka', NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Triple Sec')), 1.5, 'cl', 'Cointreau', NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Lime juice')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Cranberry juice')), 3, 'cl', NULL, NULL);

-- Cocktail: Dry Martini
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('dry-martini', 'Dry Martini', 'martini', 'Before Dinner Cocktail', NULL, 'Stir in mixing glass with ice cubes. Strain into chilled martini glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.', 'https://iba-world.com/wp-content/uploads/2020/12/dry-martini.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 6, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Vermouth')), 1, 'cl', 'Dry vermouth', NULL);

-- Cocktail: Between the Sheets
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('between-the-sheets', 'Between the Sheets', 'martini', 'All Day Cocktail', NULL, 'Shake with ice cubes. Strain into chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/between-the-sheets.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('White rum')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Cognac')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Triple Sec')), 3, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 2, 'cl', NULL, NULL);

-- Cocktail: Casino
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('casino', 'Casino', 'martini', 'All Day Cocktail', 'Lemon twist and a cherry', 'Shake with ice cubes. Strain into chilled cocktail glass.', 'https://iba-world.com/wp-content/uploads/2020/12/casino.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Gin')), 4, 'cl', 'Old Tom Gin', NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Cherry liqueur')), 1, 'cl', 'Maraschino', NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Orange Bitters')), 1, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 4, (SELECT id FROM base_ingredients WHERE slug=slugify('Lemon juice')), 1, 'cl', NULL, NULL);

-- Cocktail: Caipirinha
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('caipirinha', 'Caipirinha', 'old-fashioned', 'All Day Cocktail', NULL, 'Place lime and sugar in old fashion glass and muddle. Fill glass with ice and Cachaca (note:Caipiroska- use Vodka instead of Cachaca).', 'https://iba-world.com/wp-content/uploads/2020/12/caipirinha.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Cachaca')), 5, 'cl', NULL, NULL);

-- Cocktail: Harvey Wallbanger
WITH new_cocktail AS (
    INSERT INTO cocktails (slug, name, glass, category, garnish, preparation, image_url)
    VALUES ('harvey-wallbanger', 'Harvey Wallbanger', 'highball', 'All Day Cocktail', 'Orance slice and a cherry', 'Build vodka and orange juice into a highball glass filled with ice. Stir gently and float Galliano on top.', 'https://iba-world.com/wp-content/uploads/2020/12/harvey-wallbanger.jpg')
    RETURNING id
)
INSERT INTO ingredients (cocktail_id, position, base_ingredient_id, amount, unit, label, special)
VALUES
    ((SELECT id FROM new_cocktail), 1, (SELECT id FROM base_ingredients WHERE slug=slugify('Vodka')), 4.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 2, (SELECT id FROM base_ingredients WHERE slug=slugify('Galliano')), 1.5, 'cl', NULL, NULL),
    ((SELECT id FROM new_cocktail), 3, (SELECT id FROM base_ingredients WHERE slug=slugify('Orange juice')), 9, 'cl', NULL, NULL);
