name: Deploy Images to GHCR

on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
      push-store-images:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

          - name: Extract image tag (simple)
            id: extract_tag
            run: |
              if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
                echo "tag=latest" >> $GITHUB_OUTPUT
              elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
                echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
              else
                # For other branches, use branch name (optional)
                echo "tag=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
              fi            

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build + Push Image Cocktail API'
            run: |
              cd api
              docker build . --tag ghcr.io/remast/cocktail-api:${{ steps.extract_tag.outputs.tag }}
              docker push ghcr.io/remast/cocktail-api:${{ steps.extract_tag.outputs.tag }}
